### ISSUE TITLE
Set Image from URL

### ISSUE THREAD

**Issue by Pradiptamldt** [ezefranca/EFImageViewZoom#4]
How could I set image from url to this library?

**Comment by ciumvacTweets** [comment]
Just solved same issue; I'll create a pull request later.

by the way, setting properties and delegates in `draw` is wrong  @ezefranca

**Comment by Pradiptamldt** [comment]
@ciumvacTweets can you please tell me how do you fixed that?

**Comment by ciumvacTweets** [comment]
@Pradiptamldt 

1) I have moved UIImageView initialization from `draw ( _ rect:)` to `awakeFromNib`.
2) redeclared ` fileprivate var imageView: UIImageView!`  -> ` fileprivate (set) var imageView: UIImageView!` ( in my case, `loadImage` method is an `UIImageView` category).

... and  my `UIViewController` subclass code:
```
 zoomView._delegate = self
 zoomView.minimumZoomScale = 1.0
 zoomView.maximumZoomScale = 7.0
 zoomView.imageView.loadImage(from: item.image.imageURL, contentMode: .scaleAspectFill, clipToBounds: true)
```

`loadImage` is my wrapper over Alamofire's `af_setImage`

hope this will help you; and sorry for my English )

**Comment by Pradiptamldt** [comment]
Thanks for your comment @ciumvacTweets

**Comment by ezefranca** [comment]
I will close this issue, thanks for the tips and I will be waiting the PR @ciumvacTweets

**Comment by ciumvacTweets** [comment]
Hi; i'm so sorry, actually forgot about PR.   I found Yesterday this library in my forks, and I remembered about my promise :)
